version: '3.9'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - identity
      - recorders

  identity:
    build:
      context: ./Identity
      dockerfile: Dockerfile
    ports:
      - 7063:7063

  recorders:
    build:
      context: ./DiplomWebApi/DiplomWebApi
      dockerfile: Dockerfile
    ports:
      - 44375:44375
